import { createElement } from 'lwc';
import LdsRealTimeAccountRecord from 'c/ldsRealTimeAccountRecord';

describe('c-lds-real-time-account-record', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-lds-real-time-account-record', {
            is: LdsRealTimeAccountRecord
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});